kind = "web"
previewPath = "/"
title = "Peace"
version = "1.0.0"
id = "artifacts/peace"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24932

[services.development]
run = "pnpm --filter @workspace/peace run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/peace", "run", "build" ]
publicDir = "artifacts/peace/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24932"
BASE_PATH = "/"
